//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirenaBT5Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SirenaBT5Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.0;1189
        ///PACKET=0;3a3Dl/9TDKxhYDsvTihxS5XaEbkJwtV58guMrrSN92OYuAgn5LyDdRaMJtUK/ug4kbTnxjzeP+eVfVEieD2ux2WLHZfue+zw4VRsbDrZheAxkFdqpgSxLnH4a+rYmXtWv7/zlP7ZTUV/aWBXESBM3qMx3dmYqPieBrziIPDi5B3/HG1duJCnirRS8vjhS3hdUOMCnAQAQhtAFX/HeX7Lz0ZYbhASh0sEeOKNhGQ6v188YfmQrL7kjXtT0/racKxNgmga+njZEAnZIPXxTE4szVwtxQjiEzjN2BmYEf6C10w1Aofm8s3K/jHpRYzrZqCA9EZvaGfQVaCKk4h+4F7r83qEpWmkcy1PjxLcqtzqhpELlN7guh39MO/TdCk8xPstEI6MmT4aAFSHKvwQSq4kli/M+X1/4AvoHeSMShqciA++5TPVdDfS63vAh7q4ye7egwzZEG6MC49qshL7ExhoTap7D7S9A/CiwBeh5fzRD5DKe [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string firmware {
            get {
                return ResourceManager.GetString("firmware", resourceCulture);
            }
        }
    }
}
